// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxd_0I_iRv_NmawP2BlVb5HMK_P6es82E',
    appId: '1:819355620126:web:856cb1c5f7b3483f356f0f',
    messagingSenderId: '819355620126',
    projectId: 'apprendeplus-e226f',
    authDomain: 'apprendeplus-e226f.firebaseapp.com',
    storageBucket: 'apprendeplus-e226f.firebasestorage.app',
    measurementId: 'G-MDZWJT5HWN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxKd8x07th27uwCEVX-MMxLJ3jH4dAR-s',
    appId: '1:819355620126:android:7d99641f4e5e1fea356f0f',
    messagingSenderId: '819355620126',
    projectId: 'apprendeplus-e226f',
    storageBucket: 'apprendeplus-e226f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZlwQGMr-OZgCP7q9gC8P4gL8GUtrktc0',
    appId: '1:819355620126:ios:856e397bc8a53dba356f0f',
    messagingSenderId: '819355620126',
    projectId: 'apprendeplus-e226f',
    storageBucket: 'apprendeplus-e226f.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZlwQGMr-OZgCP7q9gC8P4gL8GUtrktc0',
    appId: '1:819355620126:ios:856e397bc8a53dba356f0f',
    messagingSenderId: '819355620126',
    projectId: 'apprendeplus-e226f',
    storageBucket: 'apprendeplus-e226f.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxd_0I_iRv_NmawP2BlVb5HMK_P6es82E',
    appId: '1:819355620126:web:e4f9aa238b0567f7356f0f',
    messagingSenderId: '819355620126',
    projectId: 'apprendeplus-e226f',
    authDomain: 'apprendeplus-e226f.firebaseapp.com',
    storageBucket: 'apprendeplus-e226f.firebasestorage.app',
    measurementId: 'G-C0FGGYQ0RM',
  );
}
